const LinkList = require('./index')
let ll = new LinkList()
ll.append(1)
ll.append(2)
ll.append(3)
ll.append(5)
ll.insert(4, 3)
ll.insert(0, 0)
ll.insert(6, 6)
ll.insert(8, 7)
ll.update(7, 7)
console.log(ll.indexOf(6))
console.log(ll.toString())