const DoublyLinkList = require('./index')
const dll = new DoublyLinkList()
dll.append(1)
dll.append(2)
dll.append(3)
dll.append(5)
dll.insert(0, 0)
dll.insert(4, 4)
dll.append(7)
dll.update(6, 6)
dll.removeAt(6)
dll.remove(6)
console.log(dll.toString())